export const OPENCODE_JSONC = `{
  // Project-level OpenCode configuration generated by ai-dev.
  // Keep this file committed when the team uses OpenCode.
  "$schema": "https://opencode.ai/config.json",
  "mcp": {}
}
`;

export const COPILOT_INSTRUCTIONS = `# GitHub Copilot Instructions

Use the repository's existing architecture, naming, and style conventions. Prefer small, focused changes and avoid rewriting unrelated files.

When changing behavior, update or add relevant tests when practical. Do not use generated folders, build outputs, dependency folders, public assets, or media files as source context.
`;

export const CURSOR_RULES = `---
description: AI development guidance generated by ai-dev
alwaysApply: true
---

Use the repository's existing architecture, naming, and style conventions. Prefer small, focused changes and avoid rewriting unrelated files.

When changing behavior, update or add relevant tests when practical. Do not use generated folders, build outputs, dependency folders, public assets, or media files as source context.
`;
